DROP TABLE IF EXISTS statistics;
CREATE TABLE IF NOT EXISTS statistics
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri               VARCHAR(255)                NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    additional_fields jsonb
);
CREATE INDEX IF NOT EXISTS uri_index ON statistics (uri);