DROP TABLE IF EXISTS requests,events_compilations, compilations, categories, events, users;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)

);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(255) NOT NULL,
    pinned BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(120)                NOT NULL,
    annotation            VARCHAR(2000)               NOT NULL,
    event_date            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id          BIGINT                      NOT NULL,
    category_id           BIGINT                      NOT NULL,
    state                 VARCHAR(20)                 NOT NULL,
    created_on            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on          TIMESTAMP WITHOUT TIME ZONE,
    description           VARCHAR(7000)               NOT NULL,
    lat                   FLOAT,
    lon                   FLOAT,
    paid                  BOOLEAN                     NOT NULL,
    participant_limit     BIGINT                      NOT NULL,
    request_moderation    BOOLEAN                     NOT NULL,
    available_for_request BOOLEAN,
    CHECK (char_length(title) > 3),
    CHECK (char_length(annotation) > 20),
    CHECK (char_length(description) > 20),
    CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT pk_events_compilations PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT                      NOT NULL,
    requester_id BIGINT                      NOT NULL,
    status       VARCHAR(20)                 NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users (id)
);